export const CATEGORIES_REPOSITORY = Symbol('CATEGORIES_REPOSITORY');
export const TYPE_REPOSITORY = Symbol('TYPE_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_TYPE_REPOSITORY = Symbol('PRODUCT_TYPE_REPOSITORY');
export const PRODUCT_CATEGORY_REPOSITORY = Symbol('PRODUCT_CATEGORY_REPOSITORY');

export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
