export const CATEGORIES_REPOSITORY = Symbol('CATEGORIES_REPOSITORY');
export const TYPE_REPOSITORY = Symbol('TYPE_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_TYPE_REPOSITORY = Symbol('PRODUCT_TYPE_REPOSITORY');
export const PRODUCT_CATEGORY_REPOSITORY = Symbol(
  'PRODUCT_CATEGORY_REPOSITORY',
);
export const PRODUCT_IMAGE_REPOSITORY = Symbol('PRODUCT_IMAGE_REPOSITORY');
export const UNIT_OF_WORK_SERVICE = Symbol('UNIT_OF_WORK_SERVICE');

export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
